export default [
  {
    id: "logicgrid",
    name: "Logic Grid",
    description: "A classic logic grid puzzle game",
    site: "https://skedwards88.github.io/logic-grid/",
    code: "https://github.com/skedwards88/logic-grid",
    numPlayers: 1,
    playTimeMinutes: 5,
    googlePlay:
      "https://play.google.com/store/apps/details?id=logicgrid.io.github.skedwards88.twa",
  },
  {
    id: "crossjig",
    name: "Crossjig",
    description: "A word-based jigsaw puzzle",
    site: "https://crossjig.com",
    code: "https://github.com/skedwards88/crossjig",
    numPlayers: 1,
    playTimeMinutes: 5,
    googlePlay:
      "https://play.google.com/store/apps/details?id=com.crossjig.twa",
  },
  {
    id: "dailypalette",
    name: "Daily Palette",
    description: "A daily spatial word puzzle",
    site: "https://palettegame.com",
    code: "https://github.com/skedwards88/palette",
    numPlayers: 1,
    playTimeMinutes: 5,
    googlePlay:
      "https://play.google.com/store/apps/details?id=com.palettegame.twa",
  },
  {
    id: "words",
    name: "Word Games",
    description: "A collection of word games",
    site: "https://skedwards88.github.io/word_games/",
    code: "https://github.com/skedwards88/word_games",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "dragon",
    name: "Dragon Hero",
    description: "A text adventure puzzle",
    site: "https://skedwards88.github.io/dragon/",
    code: "https://github.com/skedwards88/dragon",
    numPlayers: 1,
    playTimeMinutes: 20,
    googlePlay:
      "https://play.google.com/store/apps/details?id=dragon.io.github.skedwards88.twa",
  },
  {
    id: "monkeys",
    name: "Monkeys of the Caribbean",
    description: "Compete to control the most coconut routes",
    site: "https://skedwards88.github.io/monkeys/",
    code: "https://github.com/skedwards88/monkeys",
    numPlayers: 2,
    playTimeMinutes: 15,
  },
  {
    id: "sector",
    name: "Sector",
    description: "Control the largest sector of the universe",
    site: "https://skedwards88.github.io/sector/",
    code: "https://github.com/skedwards88/sector",
    numPlayers: 2,
    playTimeMinutes: 15,
  },
  {
    id: "stars_circles",
    name: "Stars and Circles",
    description: "Stake out your territory before your opponent claims it",
    site: "https://skedwards88.github.io/stars_circles_game/",
    code: "https://github.com/skedwards88/stars_circles_game",
    numPlayers: 2,
    playTimeMinutes: 15,
  },
  // {
  //   id: "stories",
  //   name: "Stories ",
  //   description: "Short stories inspired by Reddit writing prompts",
  //   site: "https://skedwards88.github.io/ShortStories/",
  //   code: "https://github.com/skedwards88/ShortStories",
  //   activityDescription: "Read now",
  // },
];
