export default [
  {
    id: "crossjig",
    name: "Crossjig",
    description: "A word-based jigsaw puzzle",
    site: "https://crossjig.com",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "lexlet",
    name: "Lexlet",
    description: "A colorful spatial word puzzle",
    site: "https://lexlet.com",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "blobble",
    name: "Blobble",
    description: "A spatial word search puzzle",
    site: "https://skedwards88.github.io/blobble/",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "logicgrid",
    name: "Logic Grid",
    description: "A classic logic grid puzzle game",
    site: "https://skedwards88.github.io/logic-grid/",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "wordfall",
    name: "Wordfall",
    description: "A meditative jumbled word search game",
    site: "https://skedwards88.github.io/wordfall/",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "gribbles",
    name: "Gribbles",
    description: "A jumbled word search game",
    site: "https://skedwards88.github.io/gribbles/",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "dragon",
    name: "Dragon Hero",
    description: "A text adventure puzzle",
    site: "https://skedwards88.github.io/dragon/",
    numPlayers: 1,
    playTimeMinutes: 20,
  },
  {
    id: "words",
    name: "Word Games",
    description: "A collection of word games",
    site: "https://skedwards88.github.io/word_games/",
    numPlayers: 1,
    playTimeMinutes: 5,
  },
  {
    id: "monkeys",
    name: "Monkeys of the Caribbean",
    description: "Compete to control the most coconut routes",
    site: "https://skedwards88.github.io/monkeys/",
    numPlayers: 2,
    playTimeMinutes: 15,
  },
  {
    id: "sector",
    name: "Sector",
    description: "Control the largest sector of the universe",
    site: "https://skedwards88.github.io/sector/",
    numPlayers: 2,
    playTimeMinutes: 15,
  },
  {
    id: "stars_circles",
    name: "Stars and Circles",
    description: "Stake out your territory before your opponent claims it",
    site: "https://skedwards88.github.io/stars_circles_game/",
    numPlayers: 2,
    playTimeMinutes: 15,
  },
  // {
  //   id: "stories",
  //   name: "Stories ",
  //   description: "Short stories inspired by Reddit writing prompts",
  //   site: "https://skedwards88.github.io/ShortStories/",
  //   activityDescription: "Read now",
  // },
];
